export const ADD_OFFER = "ADD_OFFER";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const GLOBAL_MESSAGE = "GLOBAL_MESSAGE";

export const PROFILE_DETAILS = "PROFILE_DETAILS";
export const EDIT_PROFILE = "EDIT_PROFILE";
